# Generated by Django 5.0.6 on 2024-06-15 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('color_palette', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteVersions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da variante')),
                ('color_palette', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='color_palette.colorpalette', verbose_name='Paleta de cores')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes do site',
            },
        ),
    ]
