# Generated by Django 4.2.14 on 2025-04-13 14:32

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0001_initial'),
        ('hero', '0001_initial'),
        ('banners', '0001_initial'),
        ('faq', '0001_initial'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteVersions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da variante')),
                ('color', colorfield.fields.ColorField(default='#e11d48', image_field=None, max_length=25, samples=None, verbose_name='Cor principal')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banners.banner', verbose_name='Banner')),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.faq', verbose_name='Perguntas e respostas')),
                ('features', models.ManyToManyField(to='features.feature')),
                ('hero', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hero.hero', verbose_name='Sessão Hero')),
                ('stats', models.ManyToManyField(to='stats.statitem')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes do site',
            },
        ),
    ]
