# Generated by Django 5.0.6 on 2024-06-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_versions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteversions',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
