# Generated by Django 5.0.6 on 2024-06-15 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_versions', '0003_websiteversions_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteversions',
            name='hero',
        ),
    ]
