# Generated by Django 5.0.6 on 2024-06-15 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
        ('website_versions', '0004_remove_websiteversions_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteversions',
            name='hero',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hero.hero', verbose_name='Sessão Hero'),
        ),
    ]
