# Generated by Django 5.0.6 on 2024-06-15 23:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_versions', '0005_websiteversions_hero'),
    ]

    operations = [

    ]
