# Generated by Django 5.0.6 on 2024-06-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_statitem_options'),
        ('website_versions', '0006_alter_websiteversions_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteversions',
            name='stats',
            field=models.ManyToManyField(to='stats.statitem'),
        ),
    ]
