# Generated by Django 5.0.6 on 2024-06-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_alter_feature_options'),
        ('website_versions', '0007_websiteversions_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteversions',
            name='features',
            field=models.ManyToManyField(to='features.feature'),
        ),
    ]
