# Generated by Django 5.0.6 on 2024-06-17 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
        ('website_versions', '0008_websiteversions_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteversions',
            name='banner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='banners.banner', verbose_name='Banner'),
        ),
    ]
