# Generated by Django 5.0.6 on 2024-06-17 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_versions', '0010_alter_websiteversions_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteversions',
            name='banner',
        ),
    ]
