# Generated by Django 5.0.6 on 2024-06-17 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_faqitem_answer'),
        ('website_versions', '0012_websiteversions_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteversions',
            name='faq',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faq.faq', verbose_name='Perguntas e respostas'),
            preserve_default=False,
        ),
    ]
