# Generated by Django 5.0.6 on 2024-08-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_versions', '0013_websiteversions_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteversions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
