# Generated by Django 5.0.6 on 2024-06-15 00:46

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('main_color', colorfield.fields.ColorField(default='#008cc1', image_field=None, max_length=25, samples=None, verbose_name='Cor principal')),
                ('main_bg_dark', colorfield.fields.ColorField(default='#111827', image_field=None, max_length=25, samples=None, verbose_name='Cor de fundo escura')),
                ('main_bg_light', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Cor de fundo clara')),
            ],
            options={
                'verbose_name': 'Paleta de cores',
            },
        ),
    ]
