# Generated by Django 5.0.6 on 2024-06-15 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('color_palette', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorpalette',
            options={'verbose_name': 'Paleta de cores', 'verbose_name_plural': 'Paleta de cores'},
        ),
    ]
