# Generated by Django 5.0.6 on 2024-06-15 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('color_palette', '0002_alter_colorpalette_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorpalette',
            name='main_bg_dark',
        ),
        migrations.RemoveField(
            model_name='colorpalette',
            name='main_bg_light',
        ),
    ]
