# Generated by Django 5.0.6 on 2024-06-15 05:18

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('color_palette', '0003_remove_colorpalette_main_bg_dark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorpalette',
            name='main_color',
            field=colorfield.fields.ColorField(default='#e11d48', image_field=None, max_length=25, samples=None, verbose_name='Cor principal'),
        ),
    ]
