# Generated by Django 5.0.6 on 2024-06-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ícone', max_length=255, verbose_name='ícone')),
                ('code', models.TextField(verbose_name='Código SVG')),
            ],
        ),
    ]
