# Generated by Django 4.2.14 on 2025-04-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ícone', max_length=255, verbose_name='Nome')),
                ('code', models.TextField(verbose_name='Código SVG')),
            ],
            options={
                'verbose_name': 'Ícone',
                'verbose_name_plural': 'Ícones',
            },
        ),
    ]
