# Generated by Django 5.0.6 on 2024-06-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='name',
            field=models.CharField(default='ícone', max_length=255, verbose_name='Nome'),
        ),
    ]
