# Generated by Django 5.0.6 on 2024-06-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0002_alter_icon_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icon',
            options={'verbose_name': 'Ícone', 'verbose_name_plural': 'Ícones'},
        ),
    ]
