# Generated by Django 5.0.6 on 2024-06-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Funcionalidade'},
        ),
    ]
