# Generated by Django 4.2.14 on 2025-04-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(default='Kickstart your Next.js 14 website in minutes', max_length=255, verbose_name='Título')),
                ('highlight_word', models.CharField(default='Next.js 14', max_length=255, verbose_name='Palavra destacada do título')),
                ('text', models.CharField(default='Inators UI is a collection of UI components and templates based on Tailwind and Shadcn/ui, just copy and use', max_length=255, verbose_name='Texto da hero')),
                ('command_line', models.CharField(default='npx shadcn-ui@latest init', max_length=255, verbose_name='Comando')),
                ('cta_text', models.CharField(default='Browse all Components', max_length=255, verbose_name='Texto do CTA')),
                ('cta_link', models.CharField(default='#', max_length=255, verbose_name='Link do CTA')),
                ('img', models.FileField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Sessão Hero',
                'verbose_name_plural': 'Sessões Hero',
            },
        ),
    ]
