# Generated by Django 5.0.6 on 2024-06-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='text',
            field=models.CharField(default='Next.js 14', max_length=255, verbose_name='Texto da hero'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='highlight_word',
            field=models.CharField(default='Next.js 14', max_length=255, verbose_name='Palavra destacada do título'),
        ),
    ]
