# Generated by Django 5.0.6 on 2024-06-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_hero_text_alter_hero_highlight_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='img',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='text',
            field=models.CharField(default='Inators UI is a collection of UI components and templates based on Tailwind and Shadcn/ui, just copy and use', max_length=255, verbose_name='Texto da hero'),
        ),
    ]
