# Generated by Django 5.0.6 on 2024-06-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_hero_img_alter_hero_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
