# Generated by Django 4.2.14 on 2025-04-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Pergunta')),
                ('answer', models.TextField(verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Perguntas e respostas',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='FAQ', max_length=255, verbose_name='Título')),
                ('subtitle', models.CharField(default="Here are some of our Frequently Asked Questions. If you have any other questions you'd like answered please feel free to contact me.", max_length=255, verbose_name='Subtítulo')),
                ('questions', models.ManyToManyField(to='faq.faqitem')),
            ],
            options={
                'verbose_name': 'Sessão de Perguntas e Respostas',
            },
        ),
    ]
