# Generated by Django 5.0.6 on 2024-06-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Pergunta')),
                ('answer', models.CharField(max_length=255, verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Perguntas e respostas',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtítulo')),
                ('questions', models.ManyToManyField(to='faq.faqitem')),
            ],
            options={
                'verbose_name': 'Sessão de Perguntas e Respostas',
            },
        ),
    ]
