# Generated by Django 5.0.6 on 2024-06-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqitem',
            name='answer',
            field=models.TextField(verbose_name='Resposta'),
        ),
    ]
