# Generated by Django 5.0.6 on 2024-08-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_faqitem_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='subtitle',
            field=models.CharField(default="Here are some of our Frequently Asked Questions. If you have any other questions you'd like answered please feel free to contact me.", max_length=255, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(default='FAQ', max_length=255, verbose_name='Título'),
        ),
    ]
