# Generated by Django 4.2.14 on 2025-04-13 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_number', models.CharField(max_length=255, verbose_name='Número')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icons.icon')),
            ],
            options={
                'verbose_name': 'Estatística',
                'verbose_name_plural': 'Estatísticas',
            },
        ),
    ]
