# Generated by Django 5.0.6 on 2024-06-16 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icons', '0002_alter_icon_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_number', models.CharField(max_length=255, verbose_name='Número')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icons.icon')),
            ],
        ),
    ]
