# Generated by Django 5.0.6 on 2024-06-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statitem',
            options={'verbose_name': 'Estatística', 'verbose_name_plural': 'Estatísticas'},
        ),
    ]
